#cloud-config
users:
  - name: sedunovsv
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ${ssh_public_key}

# Установка Nginx
package_update: true
packages:
  - nginx
runcmd:
  - systemctl restart nginx
  - mkdir -p /var/www/html
  - echo "<h1>Welcome to Nginx Server 1!</h1><p>This is the first Nginx instance.</p>" > /var/www/html/index.html
  - systemctl restart nginx
  - systemctl enable nginx
