---
- hosts: all
  become: yes
  roles:
    - ../roles/common

- hosts: patroni
  become: yes
  roles:
    - ../roles/patroni
    - ../roles/db_init

- hosts: haproxy
  become: yes
  roles:
    - ../roles/haproxy

- hosts: saleor
  become: yes
  roles:
    - ../roles/saleor

- hosts: storefront
  become: yes
  roles:
    - ../roles/storefront

