all:
  children:
    postgresql:
      hosts:
        pg102:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 102
          ct_ip: 192.168.50.21
          patroni_name: pg102
        pg103:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 103
          ct_ip: 192.168.50.22
          patroni_name: pg103
        pg104:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 104
          ct_ip: 192.168.50.23
          patroni_name: pg104
    etcd:
      hosts:
        etcd1:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 109
          ct_ip: 192.168.50.51
          etcd_name: etcd1
        etcd2:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 110
          ct_ip: 192.168.50.52
          etcd_name: etcd2
        etcd3:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 111
          ct_ip: 192.168.50.53
          etcd_name: etcd3
    haproxy:
      hosts:
        haproxy1:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 100
          ct_ip: 192.168.50.11
          keepalived_priority: 100
          keepalived_state: MASTER
        haproxy2:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 101
          ct_ip: 192.168.50.12
          keepalived_priority: 90
          keepalived_state: BACKUP
    docker_swarm:
      hosts:
        docker_mgr1:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 105
          ct_ip: 192.168.50.31
        docker_mgr2:
          ansible_host: localhost
          ansible_connection: local
          ct_id: 106
          ct_ip: 192.168.50.32
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Настройки для выполнения от пользователя sedunovsv
    # Пользователь должен иметь права на выполнение pct команд без пароля
    ansible_user: sedunovsv
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_user: root
    ansible_become_pass: ""  # Пароль не требуется, если настроен NOPASSWD


