---
django_project_name: "myproject"
django_app_name: "api"
django_user: "django"
django_group: "django"
django_home: "/opt/django"
uwsgi_port: 8001
nginx_backend_port: 80
postgres_db: "appdb"
postgres_user: "appuser"
postgres_password: "apppassword"
database_host: "{{ hostvars['database']['ansible_host'] }}"
