- name: Include target setup for iSCSI server
  include_tasks: iscsi_target.yml
  when: inventory_hostname == iscsi_target

- name: Include initiator setup for clients
  include_tasks: iscsi_initiator.yml
  when: inventory_hostname != iscsi_target

- name: Setup LVM
  include_tasks: lvm.yml
  when: inventory_hostname != iscsi_target

- name: Setup GFS2
  include_tasks: gfs2.yml
  when: inventory_hostname != iscsi_target and inventory_hostname == "gfs2-client-0"